// File generated by running: flutterfire configure
// For now, use this template and we'll generate the real one

import 'package:firebase_core/firebase_core.dart';

Future<void> initializeFirebase() async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
}

class DefaultFirebaseOptions {
  static FirebaseOptions? get currentPlatform => null;
}